/// Flutter icons PersonIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PersonIcons
///      fonts:
///       - asset: fonts/PersonIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PersonIcons {
  PersonIcons._();

  static const _kFontFam = 'PersonIcons';
  static const String? _kFontPkg = null;

  static const IconData calendar = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hide_password = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hide_password_unactive = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swap = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData two_user = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weight_one = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
